### PR TITLE
changed navbar style a bit

### PR DESCRIPTION
**Pull request by Olindam20**

### CODE REVIEW

**Comment by Suvradippaul** [comment]
Hey @Olindam20 
Can you please share an image/images of the webpage with your changes?

**Comment by Olindam20** [comment]
> Hey @Olindam20 Can you please share an image/images of the webpage with your changes?

i have mailed you

**Comment by Suvradippaul** [comment]
Please refer to https://github.com/Suvradippaul/Responsive-web-design/pull/3#issuecomment-1274518808

**Comment by Suvradippaul** [comment]
> > Hey @Olindam20 Can you please share an image/images of the webpage with your changes?
> 
> i have mailed you
Please share here

**Comment by Olindam20** [comment]
IMG_20221009_185020_tigr

**Comment by Suvradippaul** [comment]
Looks good !! Thank you for considering to contribute to this repo.

**Pull request merged**
